### PR TITLE
Vera zab/issue94

### PR DESCRIPTION
**Pull request by VeraZab**
closes: https://github.com/c-w/mathquill4quill/issues/94
what do you think about this one @c-w ?

### CODE REVIEW

**Review by c-w — COMMENTED** [review]
Overall LGTM. Could you also add a new test ([here](https://github.com/c-w/mathquill4quill/tree/f96f4ab34acc9cb3b2c7e8e90301e8c3bfc320df/tests)) so that we don't risk breaking this feature in the future. Thank you!

**Comment by c-w** [comment]
@VeraZab How's it going with this pull request? Any questions or concerns about my ask above?

**Comment by c-w** [comment]
@VeraZab Any desires to get this merged nevertheless or should I close the PR?

**Comment by VeraZab** [comment]
sorry, won't really be able to jump back in there atm, I think we can close for now

**Pull request closed without merging**
