### PR TITLE
Improve command operator regex

### PR DESCRIPTION
**Pull request by ahmed2m**
I just realized that the original regex only allowed things like `\\sqrt[3]{}` but not `\\int_x^y`, so I just simplified the regex to detect \\ followed by just letters

### CODE REVIEW

**Review by c-w — COMMENTED** [review]
Thanks for the fix. Could you also add a few [tests](https://github.com/c-w/mathquill4quill/tree/master/tests) so that we don't get a regression here in the future? Thanks in advance!

**Comment by ahmed2m** [comment]
> Thanks for the fix. Could you also add a few [tests](https://github.com/c-w/mathquill4quill/tree/master/tests) so that we don't get a regression here in the future? Thanks in advance!

Added two tests, had to add a dataset attribute to the operator buttons to be able to test them. The test is rather simple because if a latex string like `\sqrt[3]{}` or `\int_x^y` was sent to the `.cmd()` it won't be rendered properly in the text field, same for `\sqrt` if sent to `.write()`

**Review by c-w — APPROVED** [review]

**Comment by ahmed2m** [comment]
Any chance for this to be released soon?

**Comment by c-w** [comment]
Released in [v2.3.0](https://github.com/c-w/mathquill4quill/releases/tag/v2.3.0)

**Pull request merged**
