### PR TITLE
Add nextjs demo

### PR DESCRIPTION
**Pull request by thangnh91**
I add a nextjs demo for one who using this tool with nextjs. I simply copy some html and css codes from the reactjs demo, to keep them the same.

### CODE REVIEW

**Review by c-w — CHANGES_REQUESTED** [review]
I pushed some commits to simplify the demo and to integrate it into the rest of the project. Take a look and let me know if there's any issues with the changes.

Note that currently eslint is failing when running `npm run lint` from the root of the project:

npm run lint error

Could you add the appropriate eslint config to the nextjs folder (similar to the React one [here](https://github.com/c-w/mathquill4quill/blob/7b16ce3f36d22044778ef3a9c55068100587c124/reactjs/.eslintrc.js)) and then this is ready to be merged.

**Comment by thangnh91** [comment]
@c-w I add the eslint config to the nextjs folder. Could you take a look?

**Comment by c-w** [comment]
The CI is failing @thangnh91. Could you rebase against the latest main branch and fix the issues? Thanks in advance!

**Comment by thangnh91** [comment]
@c-w , really sorry for late reply. I reformat codes with prettier, and run the 'npm run lint', and see no error. Is this ok? Please tell me any thing if I can do. I really want to support you and the community with my little effort.

**Review by c-w — APPROVED** [review]
🎉

**Comment by jbuyu** [comment]
@thangnh91 did you get the mathEditor to build on your Nextjs project? I've added it, it works well on dev, but breaks on Prod. Here's the error I'm getting:
```
Node.js v18.17.0
   Collecting page data  ./Users/jbuyu/Desktop/projects/cider/Angaza/admin-dash/node_modules/quill/dist/quill.js:7661
var elem = document.createElement('div');
           ^

ReferenceError: document is not defined
    at Object.<anonymous> (/Users/jbuyu/Desktop/projects/cider/Angaza/admin-dash/node_modules/quill/dist/quill.js:7661:12)
    at __webpack_require__ (/Users/jbuyu/Desktop/projects/cider/Angaza/admin-dash/node_modules/quill/dist/quill.js:36:30)
    at Object.<anonymous> (/Users/jbuyu/Desktop/projects/cider/Angaza/admin-dash/node_modules/quill/dist/quill.js:1030:1)
    at __webpack_require__ (/Users/jbuyu/Desktop/projects/cider/Angaza/admin-dash/node_modules/quill/dist/quill.js:36:30)
    at Object.<anonymous> (/Users/jbuyu/Desktop/projects/cider/Angaza/admin-dash/node_modules/quill/dist/quill.js:5655:14)
    at __webpack_require__ (/Users/jbuyu/Desktop/projects/cider/Angaza/admin-dash/node_modules/quill/dist/quill.js:36:30)
    at Object.<anonymous> (/Users/jbuyu/Desktop/projects/cider/Angaza/admin-dash/node_modules/quill/dist/quill.js:10045:13)
    at __webpack_require__ (/Users/jbuyu/Desktop/projects/cider/Angaza/admin-dash/node_modules/quill/dist/quill.js:36:30)
    at Object.<anonymous> (/Users/jbuyu/Desktop/projects/cider/Angaza/admin-dash/node_modules/quill/dist/quill.js:11557:18)
    at __webpack_require__ (/Users/jbuyu/Desktop/projects/cider/Angaza/admin-dash/node_modules/quill/dist/quill.js:36:30)

Node.js v18.17.0

```

**Pull request merged**
